import type {
  ToolInvestigation,
} from "@/types";


interface ToolInvestigationPanelProps {
  investigation: ToolInvestigation;
}


interface JsonBlockProps {
  value: unknown;
}


function JsonBlock({
  value,
}: JsonBlockProps) {
  return (
    <pre className="mt-3 overflow-x-auto rounded-lg border border-slate-800 bg-slate-950 p-4 text-xs leading-6 text-slate-300">
      {JSON.stringify(
        value,
        null,
        2
      )}
    </pre>
  );
}


export default function ToolInvestigationPanel({
  investigation,
}: ToolInvestigationPanelProps) {
  const execution =
    investigation.tool_execution;

  return (
    <div className="mt-5 rounded-xl border border-violet-500/20 bg-violet-500/5 p-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <p className="text-xs font-semibold uppercase tracking-widest text-violet-400">
            Tool-Assisted Investigation
          </p>

          <p className="mt-1 text-xs text-slate-500">
            Model-selected operational evidence
          </p>
        </div>

        <span
          className={
            investigation.tool_called
              ? "rounded-full border border-violet-500/40 bg-violet-500/10 px-3 py-1 text-xs font-semibold text-violet-300"
              : "rounded-full border border-slate-700 bg-slate-800 px-3 py-1 text-xs font-semibold text-slate-300"
          }
        >
          {investigation.tool_called
            ? "Tool Used"
            : "Direct Answer"}
        </span>
      </div>


      <div className="mt-5">
        <p className="text-xs uppercase tracking-wide text-slate-500">
          Investigation Question
        </p>

        <p className="mt-2 text-sm leading-6 text-slate-300">
          {investigation.question}
        </p>
      </div>


      {execution && (
        <div className="mt-6 space-y-5">
          <div className="rounded-lg border border-slate-800 bg-slate-950/70 p-4">
            <p className="text-xs uppercase tracking-wide text-slate-500">
              Selected Tool
            </p>

            <p className="mt-2 font-mono text-sm font-semibold text-violet-300">
              {execution.name}
            </p>
          </div>


          <div>
            <h4 className="text-sm font-semibold text-slate-200">
              Tool Arguments
            </h4>

            <p className="mt-1 text-xs text-slate-500">
              Generated by the model, then validated by the backend.
            </p>

            <JsonBlock
              value={execution.arguments}
            />
          </div>


          <div>
            <h4 className="text-sm font-semibold text-slate-200">
              Tool Result
            </h4>

            <p className="mt-1 text-xs text-slate-500">
              Produced by our Python tool implementation.
            </p>

            <JsonBlock
              value={execution.result}
            />
          </div>
        </div>
      )}


      <div className="mt-6 rounded-lg border border-cyan-500/20 bg-cyan-500/5 p-4">
        <p className="text-xs font-semibold uppercase tracking-wide text-cyan-400">
          AI Conclusion
        </p>

        <p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-300">
          {investigation.final_answer}
        </p>
      </div>


      <div className="mt-5 border-t border-slate-800 pt-4 text-xs text-slate-600">
        Model: {investigation.model_name}
      </div>
    </div>
  );
}