"""add incident analyses

Revision ID: f3fd1f35f0fc
Revises: c8092940ef36
Create Date: 2026-07-08 23:30:17.146677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3fd1f35f0fc'
down_revision: Union[str, Sequence[str], None] = 'c8092940ef36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('affected_service', sa.String(length=120), nullable=False),
    sa.Column('likely_impact', sa.Text(), nullable=False),
    sa.Column('recommended_next_step', sa.Text(), nullable=False),
    sa.Column('analysis_summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_analyses_incident_id'), 'incident_analyses', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_analyses_incident_id'), table_name='incident_analyses')
    op.drop_table('incident_analyses')
    # ### end Alembic commands ###
